import type { ColorScheme, DeviceTheme } from "app.contract.theme";

export const defaultTheme = {
  firstToolbarbutton: "#dfdede",
  // Main colors
  primaryColor: "#E07B4C",
  secondaryColor: "#D2691E",
  tertiaryColor: "#CD853F",
  // Container backgrounds
  themeSideMenu: "#FFFFFF",
  pageBookBackground: "#FFFFFF",
  panelBackground: "#F8FAFC",
  // Tab
  tabSelection: "#E07B4C",
  activeTabBackground: "#FADDD1",
  activeTabText: "#E07B4C",
  activeTabBorder: "#E07B4C",
  activeTabFill: "#FADDD1",
  simpleTabText: "#333333",
  inactiveTabText: "#333333",
  // Buttons
  primaryButton: "#E07B4C",
  inputBackground: "#E8E8E8",
  primaryButtonColor: "#FFFFFF",
  primaryButtonBorder: "#E07B4C",
  sidebarShadow: "#E8E8E8",
  primaryButtonFill: "#E07B4C",
  secondaryButton: "#D2691E",
  secondaryButtonColor: "#FFFFFF",
  secondaryButtonBorder: "#D2691E",
  secondaryButtonFill: "#D2691E",
  tertiaryButtonColor: "#333333",
  buttonBorder: "#E1E3EA",
  // Scripture text
  bookHeadingColor: "#333333",
  chapterHeadingColor: "#333333",
  verseNumberColor: "#000000",
  verseTextColor: "#333333",
  pageBackground: "#FFFFFF",
  pageTextColor: "#333333",
  // Side menu
  heading1Color: "#333333",
  heading2Color: "#333333",
  heading3Color: "#333333",
  descriptionTextColor: "#666666",
  menuTextColor: "#333333",
  breadcrumbsColor: "#666666",
  sectionBackground: "#E07B4C",
  spaceNameColor: "#333333",
  sideMenuIconsColor: "#333333",
  selectedSpaceColor: "#E07B4C",
  unselectedSpaceColor: "#E1E3EA",
  spaceNameText: "#333333",
  addButtonBackground: "#E07B4C",
  addButtonIcon: "#E07B4C",
  selectPanelIcon: "#333333",
  openCloseMenuIcon: "#333333",
  moreIcon: "#666666",
  settingsIcon: "#666666",
  inactiveSpaceIndicator: "#E1E3EA",
  activeSpaceIndicator: "#E07B4C",
  profileAvatar: "#E07B4C",
  // Selection UI & toolbar
  toolbarBorder: "#E1E3EA",
  toolbarFill: "#FFFFFF",
  toolbarIconsColor: "#333333",
  selectionUIBorder: "#E1E3EA",
  selectionUIFill: "#FFFFFF",
  selectionIconsColor: "#333333",
  toolbarBackground: "#FFFFFF",
  iconColor: "#333333",
  // Input fields
  inputTitleColor: "#333333",
  inputPlaceholderColor: "#999999",
  inputActiveBorder: "#E07B4C",
  inputActiveFill: "#FFFFFF",
  inputInactiveBorder: "#E1E3EA",
  inputInactiveFill: "#FFFFFF",

  inputBorder: "#E1E3EA",
  inputText: "#333333",
  inputPlaceholder: "#999999",
  // Branding
  logoColor: "#333333",
  accentColor: "#E07B4C",
  // Space selection
  spaceSelection: "#E07B4C",
  // Text colors
  text1: "#333333",
  text2: "#666666",
  showTabIcons: true,
  "filter-mode": "invert(0)",
  primaryLight: "#FADDD1",
  onPrimaryLight: "#8B4513",
  primaryBase: "#E07B4C",
  onPrimaryBase: "#FFFFFF",
  primaryDark: "#C65D2D",
  onPrimaryDark: "#FFFFFF",
  secondaryLight: "#FFE4C4",
  onSecondaryLight: "#8B4513",
  secondaryBase: "#D2691E",
  onSecondaryBase: "#FFFFFF",
  secondaryDark: "#A0522D",
  onSecondaryDark: "#FFFFFF",
  tertiaryLight: "#FFEFD5",
  onTertiaryLight: "#8B4513",
  tertiaryBase: "#CD853F",
  onTertiaryBase: "#FFFFFF",
  tertiaryDark: "#A0522D",
  onTertiaryDark: "#FFFFFF",
  background: "#FFFFFF",
  onBackground: "#333333",
  surface: "#FAFAFA",
  onSurface: "#333333",
  text3: "#333333",
  "secondary-filter-mode": "invert(100%)",
};
export const darkTheme = {
  firstToolbarbutton: "#5C5C5C",
  // Main colors
  primaryColor: "#5A67D8",
  secondaryColor: "#A78BFA",
  tertiaryColor: "#34D399",
  // Container backgrounds
  themeSideMenu: "#2D2D2D",
  panelBackground: "#1A1A1A",
  pageBookBackground: "#303030",
  // Tab
  tabSelection: "#5A67D8",
  activeTabBackground: "#404040",
  activeTabText: "#FFFFFF",
  activeTabBorder: "#5A67D8",
  activeTabFill: "#5A67D894",
  inputBackground: "#2C2C2C",
  simpleTabText: "#AAAAAA",
  inactiveTabText: "#AAAAAA",
  // Buttons
  primaryButton: "#404040",
  sidebarShadow: "#1A1A1A",
  primaryButtonColor: "#FFFFFF",
  primaryButtonBorder: "#5A67D8",
  primaryButtonFill: "#5A67D8",
  secondaryButton: "#5A67D8",
  secondaryButtonColor: "#FFFFFF",
  secondaryButtonBorder: "#5A67D8",
  secondaryButtonFill: "#5A67D8",
  tertiaryButtonColor: "#FFFFFF",
  buttonBorder: "#5A67D8",
  // Scripture text
  bookHeadingColor: "#FFFFFF",
  chapterHeadingColor: "#FFFFFF",
  verseNumberColor: "#FFFFFF",
  verseTextColor: "#FFFFFF",
  pageBackground: "#121212",
  pageTextColor: "#FFFFFF",
  // Side menu
  heading1Color: "#FFFFFF",
  heading2Color: "#FFFFFF",
  heading3Color: "#FFFFFF",
  descriptionTextColor: "#AAAAAA",
  menuTextColor: "#FFFFFF",
  breadcrumbsColor: "#AAAAAA",
  sectionBackground: "#5A67D8",
  spaceNameColor: "#FFFFFF",
  sideMenuIconsColor: "#FFFFFF",
  selectedSpaceColor: "#FFFFFF",
  unselectedSpaceColor: "#666666",
  spaceNameText: "#FFFFFF",
  addButtonBackground: "#404040",
  addButtonIcon: "#FFFFFF",
  selectPanelIcon: "#FFFFFF",
  openCloseMenuIcon: "#FFFFFF",
  moreIcon: "#AAAAAA",
  settingsIcon: "#AAAAAA",
  inactiveSpaceIndicator: "#666666",
  activeSpaceIndicator: "#5A67D8",
  profileAvatar: "#5A67D8",
  // Selection UI & toolbar
  toolbarBorder: "#FFFFFF24",
  toolbarFill: "#2D2D2D",
  toolbarIconsColor: "#FFFFFF",
  selectionUIBorder: "#FFFFFF24",
  selectionUIFill: "#2D2D2D",
  selectionIconsColor: "#FFFFFF",
  toolbarBackground: "#1A1A1A",
  iconColor: "#FFFFFF",
  "filter-mode": "invert(100%)",
  "secondary-filter-mode": "invert(0%)",
  // Input fields
  inputTitleColor: "#FFFFFF",
  inputPlaceholderColor: "#AAAAAA",
  inputActiveBorder: "#5A67D8",
  inputActiveFill: "#2D2D2D",
  inputInactiveBorder: "#666666",
  inputInactiveFill: "#2D2D2D",

  inputBorder: "#666666",
  inputText: "#FFFFFF",
  inputPlaceholder: "#AAAAAA",
  // Branding
  logoColor: "#FFFFFF",
  accentColor: "#5A67D8",
  // Space selection
  spaceSelection: "#5A67D8",
  // Text colors
  text1: "#FFFFFF",
  text2: "#AAAAAA",
  showTabIcons: true,
  // Semantic colors
  primaryLight: "#93C5FD",
  onPrimaryLight: "#3B82F6",
  primaryBase: "#60A5FA",
  onPrimaryBase: "#111827",
  primaryDark: "#3B82F6",
  onPrimaryDark: "#FFFFFF",
  secondaryLight: "#C4B5FD",
  onSecondaryLight: "#8B5CF6",
  secondaryBase: "#A78BFA",
  onSecondaryBase: "#111827",
  secondaryDark: "#8B5CF6",
  onSecondaryDark: "#FFFFFF",
  tertiaryLight: "#6EE7B7",
  onTertiaryLight: "#10B981",
  tertiaryBase: "#34D399",
  onTertiaryBase: "#111827",
  tertiaryDark: "#FFFFFF",
  onTertiaryDark: "#10B981",
  background: "#0F172A",
  onBackground: "#FFFFFF",
  surface: "#1E293B",
  onSurface: "#FFFFFF",
  text3: "#F1F5F9",
};

export const LigonierTheme = {
  firstToolbarbutton: "#dfdede",
  primaryColor: "#FFFFFF",
  secondaryColor: "#2E4879",
  tertiaryColor: "#C0C8D7",
  themeSideMenu: "#FFFFFF",
  panelBackground: "#FFFFFF",
  tabSelection: "#2E4879",
  inputBackground: "#E8E8E8",
  activeTabBackground: "#2E48791A",
  activeTabText: "#2E4879",
  activeTabBorder: "#2E4879",
  activeTabFill: "#2E48791A",
  simpleTabText: "#333333",
  sidebarShadow: "#E8E8E8",
  pageBookBackground: "#FFFFFF",
  inactiveTabText: "#333333",
  primaryButton: "#2E4879",
  primaryButtonColor: "#FFFFFF",
  primaryButtonBorder: "#2E4879",
  primaryButtonFill: "#2E4879",
  secondaryButton: "#1F3358",
  secondaryButtonColor: "#FFFFFF",
  secondaryButtonBorder: "#1F3358",
  secondaryButtonFill: "#1F3358",
  tertiaryButtonColor: "#333333",
  buttonBorder: "#E1E3EA",
  bookHeadingColor: "#333333",
  chapterHeadingColor: "#333333",
  verseNumberColor: "#000000",
  verseTextColor: "#333333",
  pageBackground: "#FFFFFF",
  pageTextColor: "#333333",
  heading1Color: "#333333",
  heading2Color: "#333333",
  heading3Color: "#333333",
  descriptionTextColor: "#666666",
  menuTextColor: "#333333",
  breadcrumbsColor: "#666666",
  sectionBackground: "#2E4879",
  spaceNameColor: "#333333",
  sideMenuIconsColor: "#333333",
  selectedSpaceColor: "#2E4879",
  unselectedSpaceColor: "#E1E3EA",
  spaceNameText: "#333333",
  addButtonBackground: "#2E4879",
  addButtonIcon: "#E07B4C",
  selectPanelIcon: "#333333",
  openCloseMenuIcon: "#333333",
  moreIcon: "#666666",
  settingsIcon: "#666666",
  inactiveSpaceIndicator: "#E1E3EA",
  activeSpaceIndicator: "#2E4879",
  profileAvatar: "#2E4879",
  toolbarBorder: "#E1E3EA",
  toolbarFill: "#FFFFFF",
  toolbarIconsColor: "#333333",
  selectionUIBorder: "#E1E3EA",
  selectionUIFill: "#FFFFFF",
  selectionIconsColor: "#333333",
  toolbarBackground: "#FFFFFF",
  iconColor: "#333333",
  inputTitleColor: "#333333",
  inputPlaceholderColor: "#999999",
  inputActiveBorder: "#2E4879",
  inputActiveFill: "#FFFFFF",
  inputInactiveBorder: "#E1E3EA",
  inputInactiveFill: "#FFFFFF",

  inputBorder: "#E1E3EA",
  inputText: "#333333",
  inputPlaceholder: "#999999",
  logoColor: "#333333",
  accentColor: "#2E4879",
  spaceSelection: "#2E4879",
  text1: "#333333",
  text2: "#666666",
  showTabIcons: true,
  torahBorder: "#E1E3EA",
  torahFill: "#2E4879",
  torahFont: "DM Sans",
  torahSize: "12",
  neviimBorder: "#E1E3EA",
  neviimFill: "#9CB32C",
  neviimFont: "DM Sans",
  neviimSize: "12",
  ketuvimBorder: "#E1E3EA",
  ketuvimFill: "#00BCD4",
  ketuvimFont: "DM Sans",
  ketuvimSize: "12",
  bookTextColor: "#4A4A4A",
  bookTextFont: "DM Sans",
  bookTextSize: "12",
  chapterTextColor: "#4A4A4A",
  chapterTextFont: "DM Sans",
  chapterTextSize: "12",
  chapterColorBorder: "#E1E3EA",
  chapterColorFill: "#E1E3EA",
  pentateuchBorder: "#E1E3EA",
  pentateuchFill: "#2E4879",
  pentateuchFont: "DM Sans",
  pentateuchSize: "12",
  historicalBorder: "#E1E3EA",
  historicalFill: "#4CAF50",
  historicalFont: "DM Sans",
  historicalSize: "12",
  poeticBorder: "#E1E3EA",
  poeticFill: "#9C27B0",
  poeticFont: "DM Sans",
  poeticSize: "12",
  propheticBorder: "#E1E3EA",
  propheticFill: "#1976D2",
  propheticFont: "DM Sans",
  propheticSize: "12",
  primaryLight: "#C0C8D7",
  onPrimaryLight: "#8B4513",
  primaryBase: "#2E4879",
  onPrimaryBase: "#FFFFFF",
  primaryDark: "#C65D2D",
  onPrimaryDark: "#FFFFFF",
  secondaryLight: "#FFE4C4",
  onSecondaryLight: "#8B4513",
  secondaryBase: "#1F3358",
  onSecondaryBase: "#FFFFFF",
  secondaryDark: "#A0522D",
  onSecondaryDark: "#FFFFFF",
  tertiaryLight: "#FFEFD5",
  onTertiaryLight: "#8B4513",
  tertiaryBase: "#CD853F",
  onTertiaryBase: "#FFFFFF",
  tertiaryDark: "#A0522D",
  onTertiaryDark: "#FFFFFF",
  background: "#FFFFFF",
  onBackground: "#333333",
  surface: "#FAFAFA",
  onSurface: "#333333",
  "filter-mode": "invert(0)",
  text3: "#333333",
  "secondary-filter-mode": "invert(100%)",
};

export const Ligonier2Theme = {
  firstToolbarbutton: "#D9D5CE",
  // Main colors
  primaryColor: "#F0EDE8",
  secondaryColor: "#4A7C3F",
  tertiaryColor: "#C8C1B6",
  // Container backgrounds
  themeSideMenu: "#F0EDE8",
  panelBackground: "#F0EDE8",
  // Tab
  tabSelection: "#2B2B2B",
  pageBookBackground: "#FFFFFF",
  activeTabBackground: "#2B2B2B1A",
  activeTabText: "#2B2B2B",
  activeTabBorder: "#2B2B2B",
  activeTabFill: "#2B2B2B1A",
  simpleTabText: "#2B2B2B",
  inputBackground: "#E8E8E8",
  inactiveTabText: "#6B6558",
  // Buttons
  primaryButton: "#4A7C3F",
  primaryButtonColor: "#FFFFFF",
  primaryButtonBorder: "#4A7C3F",
  sidebarShadow: "#E8E8E8",
  primaryButtonFill: "#4A7C3F",
  secondaryButton: "#3A6130",
  secondaryButtonColor: "#FFFFFF",
  secondaryButtonBorder: "#3A6130",
  secondaryButtonFill: "#3A6130",
  tertiaryButtonColor: "#2B2B2B",
  buttonBorder: "#C8C1B6",
  // Scripture text
  bookHeadingColor: "#2B2B2B",
  chapterHeadingColor: "#2B2B2B",
  verseNumberColor: "#8B7355",
  verseTextColor: "#2B2B2B",
  pageBackground: "#F0EDE8",
  pageTextColor: "#2B2B2B",
  // Side menu
  heading1Color: "#2B2B2B",
  heading2Color: "#2B2B2B",
  heading3Color: "#6B6558",
  descriptionTextColor: "#6B6558",
  menuTextColor: "#2B2B2B",
  breadcrumbsColor: "#6B6558",
  sectionBackground: "#4A7C3F",
  spaceNameColor: "#2B2B2B",
  sideMenuIconsColor: "#2B2B2B",
  selectedSpaceColor: "#4A7C3F",
  unselectedSpaceColor: "#C8C1B6",
  spaceNameText: "#2B2B2B",
  addButtonBackground: "#4A7C3F",
  addButtonIcon: "#E07B4C",
  selectPanelIcon: "#2B2B2B",
  openCloseMenuIcon: "#2B2B2B",
  moreIcon: "#6B6558",
  settingsIcon: "#6B6558",
  inactiveSpaceIndicator: "#C8C1B6",
  activeSpaceIndicator: "#4A7C3F",
  profileAvatar: "#4A7C3F",
  // Selection UI & toolbar
  toolbarBorder: "#C8C1B6",
  toolbarFill: "#F0EDE8",
  toolbarIconsColor: "#2B2B2B",
  selectionUIBorder: "#C8C1B6",
  selectionUIFill: "#F0EDE8",
  selectionIconsColor: "#2B2B2B",
  toolbarBackground: "#F0EDE8",
  iconColor: "#2B2B2B",
  // Input fields
  inputTitleColor: "#2B2B2B",
  inputPlaceholderColor: "#8B7355",
  inputActiveBorder: "#4A7C3F",
  inputActiveFill: "#F0EDE8",
  inputInactiveBorder: "#C8C1B6",
  inputInactiveFill: "#F0EDE8",

  inputBorder: "#C8C1B6",
  inputText: "#2B2B2B",
  inputPlaceholder: "#8B7355",
  // Branding
  logoColor: "#2B2B2B",
  accentColor: "#4A7C3F",
  // Space selection
  spaceSelection: "#4A7C3F",
  // Text colors
  text1: "#2B2B2B",
  text2: "#6B6558",
  showTabIcons: true,
  torahBorder: "#C8C1B6",
  torahFill: "#4A7C3F",
  torahFont: "DM Sans",
  torahSize: "12",
  neviimBorder: "#C8C1B6",
  neviimFill: "#7A9E3F",
  neviimFont: "DM Sans",
  neviimSize: "12",
  ketuvimBorder: "#C8C1B6",
  ketuvimFill: "#8B7355",
  ketuvimFont: "DM Sans",
  ketuvimSize: "12",
  bookTextColor: "#2B2B2B",
  bookTextFont: "DM Sans",
  bookTextSize: "12",
  chapterTextColor: "#2B2B2B",
  chapterTextFont: "DM Sans",
  chapterTextSize: "12",
  chapterColorBorder: "#C8C1B6",
  chapterColorFill: "#C8C1B6",
  pentateuchBorder: "#C8C1B6",
  pentateuchFill: "#4A7C3F",
  pentateuchFont: "DM Sans",
  pentateuchSize: "12",
  historicalBorder: "#C8C1B6",
  historicalFill: "#7A9E3F",
  historicalFont: "DM Sans",
  historicalSize: "12",
  poeticBorder: "#C8C1B6",
  poeticFill: "#8B7355",
  poeticFont: "DM Sans",
  poeticSize: "12",
  propheticBorder: "#C8C1B6",
  propheticFill: "#6B8E5A",
  propheticFont: "DM Sans",
  propheticSize: "12",
  primaryLight: "#C8C1B6",
  onPrimaryLight: "#2B2B2B",
  primaryBase: "#4A7C3F",
  onPrimaryBase: "#FFFFFF",
  primaryDark: "#3A6130",
  onPrimaryDark: "#FFFFFF",
  secondaryLight: "#E8E4DE",
  onSecondaryLight: "#2B2B2B",
  secondaryBase: "#3A6130",
  onSecondaryBase: "#FFFFFF",
  secondaryDark: "#2A4A22",
  onSecondaryDark: "#FFFFFF",
  tertiaryLight: "#F5F2EE",
  onTertiaryLight: "#6B6558",
  tertiaryBase: "#8B7355",
  onTertiaryBase: "#FFFFFF",
  tertiaryDark: "#6B5840",
  onTertiaryDark: "#FFFFFF",
  background: "#F0EDE8",
  onBackground: "#2B2B2B",
  surface: "#E8E4DE",
  onSurface: "#2B2B2B",
  "filter-mode": "invert(0)",
  text3: "#2B2B2B",
  "secondary-filter-mode": "invert(100%)",
};

/**
 * Gets the prefered color scheme from the browser.
 */
export function getPreferedColorScheme(): ColorScheme {
  return window.matchMedia("(prefers-color-scheme: dark)").matches
    ? "dark"
    : "light";
}

/**
 * Get's the requested theme object.
 */
export function getThemeObject(theme: DeviceTheme) {
  switch (theme) {
    case "light":
      return defaultTheme;
    case "dark":
      return darkTheme;
    case "ligonier":
      return LigonierTheme;
    case "ligonier2":
      return Ligonier2Theme;
  }
  return defaultTheme;
}
