import type { ArrangementInfoConfig } from "../../models/arrangement";

export const defaultArrangement: ArrangementInfoConfig = {
  name: "traditional",
  testaments: [
    {
      name: "New Testament",
      translationKey: "new-testament",
      sections: [
        {
          name: "Apocalypse",
          translationKey: "apocalypse",
          color: "#B1B2FF",
          books: [{ bookId: "REV", type: "complete" }],
        },
        {
          name: "Letters",
          translationKey: "letters",
          color: "#AAC4FF",
          customExplodedViewScaleFactor: 8,
          customColorRange: 120,
          books: [
            {
              bookId: "JUD",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 0 },
            },
            {
              bookId: "3JN",
              type: "complete",
              explodedViewCustomScale: { x: 0.9, y: 0.15 },
              explodedViewPosition: { x: 0, y: 0.375, z: 0.1 },
              group: 1,
            },
            {
              bookId: "2JN",
              type: "complete",
              explodedViewCustomScale: { x: 0.25, y: 0.65 },
              explodedViewPosition: { x: 0.325, y: -0.125, z: 0.1 },
              group: 1,
            },
            {
              bookId: "1JN",
              type: "complete",
              explodedViewCustomScale: { x: 0.55, y: 0.65 },
              explodedViewPosition: { x: -0.175, y: -0.125, z: 0.1 },
              group: 1,
            },
            {
              bookId: "2PE",
              type: "complete",
              explodedViewCustomScale: { x: 0.75, y: 0.2625 },
              explodedViewPosition: { x: 0.1, y: 0.268, z: 0.19 },
              group: 2,
            },
            {
              bookId: "1PE",
              type: "complete",
              explodedViewCustomScale: { x: 0.75, y: 0.4375 },
              explodedViewPosition: { x: -0.1, y: -0.181, z: 0.19 },
              group: 2,
            },
            {
              bookId: "JAS",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 0.29 },
            },
            {
              bookId: "HEB",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 0.333 },
            },
            {
              bookId: "PHM",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 0.376 },
            },
            {
              bookId: "TIT",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 0.42 },
            },
            {
              bookId: "2TI",
              type: "complete",
              explodedViewCustomScale: { x: 0.7, y: 0.35 },
              explodedViewPosition: { x: 0.1, y: 0.225, z: 0.51 },
              group: 3,
            },
            {
              bookId: "1TI",
              type: "complete",
              explodedViewCustomScale: { x: 0.7, y: 0.35 },
              explodedViewPosition: { x: -0.1, y: -0.225, z: 0.51 },
              group: 3,
            },
            {
              bookId: "2TH",
              type: "complete",
              explodedViewCustomScale: { x: 0.35, y: 0.6 },
              explodedViewPosition: { x: 0.225, y: 0.05, z: 0.59 },
              group: 4,
            },
            {
              bookId: "1TH",
              type: "complete",
              explodedViewCustomScale: { x: 0.35, y: 0.6 },
              explodedViewPosition: { x: -0.225, y: -0.05, z: 0.59 },
              group: 4,
            },
            {
              bookId: "COL",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 0.69 },
            },
            {
              bookId: "PHP",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 0.733 },
            },
            {
              bookId: "EPH",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 0.776 },
            },
            {
              bookId: "GAL",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 0.82 },
            },
            {
              bookId: "2CO",
              type: "complete",
              explodedViewCustomScale: { x: 0.7, y: 0.35 },
              explodedViewPosition: { x: 0.1, y: 0.225, z: 0.91 },
              group: 5,
            },
            {
              bookId: "1CO",
              type: "complete",
              explodedViewCustomScale: { x: 0.7, y: 0.35 },
              explodedViewPosition: { x: -0.1, y: -0.225, z: 0.91 },
              group: 5,
            },
            {
              bookId: "ROM",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 1 },
            },
          ],
        },
        {
          name: "History",
          translationKey: "history",
          color: "#a0aeeb",
          books: [{ bookId: "ACT", type: "complete" }],
        },
        {
          name: "Gospels",
          translationKey: "gospels",
          color: "#a4accf",
          customExplodedViewScaleFactor: 3,
          books: [
            {
              bookId: "JHN",
              type: "complete",
              explodedViewPosition: { x: 0.3, y: 0, z: 0.1 },
            },
            {
              bookId: "LUK",
              type: "complete",
              explodedViewPosition: { x: 0, y: -0.3, z: 0.36 },
            },
            {
              bookId: "MRK",
              type: "complete",
              explodedViewPosition: { x: -0.3, y: 0, z: 0.632 },
            },
            {
              bookId: "MAT",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0.3, z: 0.9 },
            },
          ],
        },
      ],
    },
    {
      name: "Old Testament",
      translationKey: "old-testament",
      sections: [
        {
          name: "Prophets",
          translationKey: "prophets",
          color: "#EF9595",
          customExplodedViewScaleFactor: 3,
          customColorRange: 80,
          books: [
            {
              bookId: "MAL",
              type: "complete",
              explodedViewCustomScale: { x: 0.9, y: 0.15 },
              explodedViewPosition: { x: 0, y: 0.375, z: 0 },
            },
            {
              bookId: "ZEC",
              type: "complete",
              explodedViewCustomScale: { x: 0.55, y: 0.65 },
              explodedViewPosition: { x: 0.175, y: -0.125, z: 0 },
            },
            {
              bookId: "HAG",
              type: "complete",
              explodedViewCustomScale: { x: 0.25, y: 0.65 },
              explodedViewPosition: { x: -0.325, y: -0.125, z: 0 },
            },
            {
              bookId: "ZEP",
              type: "complete",
              explodedViewCustomScale: { x: 0.9, y: 0.15 },
              explodedViewPosition: { x: 0, y: 0.375, z: 0.12 },
            },
            {
              bookId: "HAB",
              type: "complete",
              explodedViewCustomScale: { x: 0.25, y: 0.65 },
              explodedViewPosition: { x: 0.325, y: -0.125, z: 0.12 },
            },
            {
              bookId: "NAH",
              type: "complete",
              explodedViewCustomScale: { x: 0.55, y: 0.65 },
              explodedViewPosition: { x: -0.175, y: -0.125, z: 0.12 },
            },
            {
              bookId: "MIC",
              type: "complete",
              explodedViewCustomScale: { x: 0.9, y: 0.15 },
              explodedViewPosition: { x: 0, y: -0.375, z: 0.24 },
            },
            {
              bookId: "JON",
              type: "complete",
              explodedViewCustomScale: { x: 0.25, y: 0.65 },
              explodedViewPosition: { x: 0.325, y: 0.125, z: 0.24 },
            },
            {
              bookId: "OBA",
              type: "complete",
              explodedViewCustomScale: { x: 0.55, y: 0.65 },
              explodedViewPosition: { x: -0.175, y: 0.125, z: 0.24 },
            },
            {
              bookId: "AMO",
              type: "complete",
              explodedViewCustomScale: { x: 0.9, y: 0.15 },
              explodedViewPosition: { x: 0, y: -0.375, z: 0.36 },
            },
            {
              bookId: "JOL",
              type: "complete",
              explodedViewCustomScale: { x: 0.55, y: 0.65 },
              explodedViewPosition: { x: 0.175, y: 0.125, z: 0.36 },
            },
            {
              bookId: "HOS",
              type: "complete",
              explodedViewCustomScale: { x: 0.25, y: 0.65 },
              explodedViewPosition: { x: -0.325, y: 0.125, z: 0.36 },
            },
            {
              bookId: "DAN",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 0.55 },
            },
            {
              bookId: "EZK",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 0.65 },
            },
            {
              bookId: "LAM",
              type: "complete",
              explodedViewCustomScale: { x: 0.4, y: 0.6 },
              explodedViewPosition: { x: 0.25, y: 0.05, z: 0.77 },
            },
            {
              bookId: "JER",
              type: "complete",
              explodedViewCustomScale: { x: 0.4, y: 0.6 },
              explodedViewPosition: { x: -0.25, y: -0.05, z: 0.79 },
            },
            {
              bookId: "ISA",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 0.95 },
            },
          ],
        },
        {
          name: "Wisdom",
          translationKey: "wisdom",
          color: "#EFB495",
          customExplodedViewScaleFactor: 2.5,
          customColorRange: 80,
          books: [
            {
              bookId: "SNG",
              type: "complete",
              explodedViewCustomScale: { x: 0.7, y: 0.9 },
              explodedViewPosition: { x: 0.15, y: 0, z: 0 },
            },
            {
              bookId: "ECC",
              type: "complete",
              explodedViewCustomScale: { x: 0.7, y: 0.9 },
              explodedViewPosition: { x: 0, y: 0, z: 0.075 },
            },
            {
              bookId: "PRO",
              type: "complete",
              explodedViewCustomScale: { x: 0.7, y: 0.9 },
              explodedViewPosition: { x: -0.15, y: 0, z: 0.1875 },
            },
            {
              bookId: "5PS",
              type: "subset",
              translationRule: "5 {name}",
              completeBookId: "PSA",
              startIndex: 106,
              endIndex: 149,
              explodedViewPosition: { x: -0.3, y: -0.35, z: 0.42 },
              group: 4,
            },
            {
              bookId: "4PS",
              type: "subset",
              translationRule: "4 {name}",
              completeBookId: "PSA",
              startIndex: 89,
              endIndex: 105,
              explodedViewPosition: { x: 0.3, y: -0.35, z: 0.46 },
              group: 4,
            },
            {
              bookId: "3PS",
              type: "subset",
              translationRule: "3 {name}",
              completeBookId: "PSA",
              startIndex: 72,
              endIndex: 88,
              explodedViewPosition: { x: 0.5, y: 0.25, z: 0.5 },
              group: 4,
            },
            {
              bookId: "2PS",
              type: "subset",
              translationRule: "2 {name}",
              completeBookId: "PSA",
              startIndex: 41,
              endIndex: 71,
              explodedViewPosition: { x: 0, y: 0.35, z: 0.54 },
              group: 4,
            },
            {
              bookId: "1PS",
              type: "subset",
              translationRule: "1 {name}",
              completeBookId: "PSA",
              startIndex: 0,
              endIndex: 40,
              explodedViewPosition: { x: -0.5, y: 0.25, z: 0.58 },
              group: 4,
            },
            {
              bookId: "JOB",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 0.9 },
            },
          ],
        },
        {
          name: "History",
          translationKey: "history",
          color: "#EFD595",
          customExplodedViewScaleFactor: 2.5,
          customColorRange: 80,
          books: [
            {
              bookId: "EST",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 0 },
            },
            {
              bookId: "NEH",
              type: "complete",
              explodedViewCustomScale: { x: 1.1, y: 0.35 },
              explodedViewPosition: { x: 0.1, y: -0.2, z: 0.14 },
            },
            {
              bookId: "EZR",
              type: "complete",
              explodedViewCustomScale: { x: 1.1, y: 0.35 },
              explodedViewPosition: { x: -0.1, y: 0.2, z: 0.16 },
            },
            {
              bookId: "2CH",
              type: "complete",
              explodedViewPosition: { x: 0.35, y: 0.05, z: 0.37 },
              group: 3,
            },
            {
              bookId: "1CH",
              type: "complete",
              explodedViewPosition: { x: -0.35, y: -0.05, z: 0.39 },
              group: 3,
            },
            {
              bookId: "2KI",
              type: "complete",
              explodedViewPosition: { x: 0.35, y: 0.05, z: 0.49 },
              group: 2,
            },
            {
              bookId: "1KI",
              type: "complete",
              explodedViewPosition: { x: -0.35, y: -0.05, z: 0.51 },
              group: 2,
            },
            {
              bookId: "2SA",
              type: "complete",
              explodedViewPosition: { x: 0.35, y: 0.05, z: 0.61 },
              group: 1,
            },
            {
              bookId: "1SA",
              type: "complete",
              explodedViewPosition: { x: -0.35, y: -0.05, z: 0.63 },
              group: 1,
            },
            {
              bookId: "RUT",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 0.8 },
            },
            {
              bookId: "JDG",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 0.9 },
            },
            {
              bookId: "JOS",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 1 },
            },
          ],
        },
        {
          name: "Law",
          translationKey: "law",
          color: "#E5E67E",
          customExplodedViewScaleFactor: 2.5,
          books: [
            {
              bookId: "DEU",
              type: "complete",
              explodedViewPosition: { x: 0.4, y: 0.4, z: 0 },
            },
            {
              bookId: "NUM",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 0.25 },
            },
            {
              bookId: "LEV",
              type: "complete",
              explodedViewPosition: { x: -0.4, y: -0.4, z: 0.5 },
            },
            {
              bookId: "EXO",
              type: "complete",
              explodedViewPosition: { x: 0, y: 0, z: 0.75 },
            },
            {
              bookId: "GEN",
              type: "complete",
              explodedViewPosition: { x: 0.4, y: 0.4, z: 1 },
            },
          ],
        },
      ],
    },
  ],
};
