export const BOOK_NAMES: Record<string, string> = {
  EXO: "Exodus",
  LEV: "Leviticus",
  NUM: "Numbers",
  DEU: "Deuteronomy",
  JOS: "Joshua",
  "1SA": "1 Samuel",
  "2SA": "2 Samuel",
  "1KI": "1 Kings",
  "2KI": "2 Kings",
  "1CH": "1 Chronicles",
  "2CH": "2 Chronicles",
  EZR: "Ezra",
  NEH: "Nehemiah",
  PSA: "Psalms",
  ISA: "Isaiah",
  JER: "Jeremiah",
  EZK: "Ezekiel",
  HAG: "Haggai",
  ZEC: "Zechariah",
  MAT: "Matthew",
  MRK: "Mark",
  LUK: "Luke",
  JHN: "John",
  ACT: "Acts",
  HEB: "Hebrews",
  REV: "Revelation",
};
