import type {
  ExperienceKey,
  ExperienceKeyMap,
} from "../../../domain/models/experience";
import { EXPERIENCE_KEYS } from "../../../domain/models/experience";
import { TABERNACLE_PIECE_KEYS } from "../../../domain/models/piece";

export type LayersMap = {
  [E in ExperienceKey]: ExperienceKeyMap[E][][];
};

export const LAYERS_MAP: LayersMap = {
  [EXPERIENCE_KEYS.TABERNACLE]: [
    [TABERNACLE_PIECE_KEYS.GROUND, TABERNACLE_PIECE_KEYS.FENCE],
    [
      TABERNACLE_PIECE_KEYS.ALTAR_OF_SACRIFICE,
      TABERNACLE_PIECE_KEYS.ARK_OF_COVENANT,
      TABERNACLE_PIECE_KEYS.BRONZE_LAVER,
      TABERNACLE_PIECE_KEYS.INCENSE_ALTAR,
      TABERNACLE_PIECE_KEYS.MENORAH,
      TABERNACLE_PIECE_KEYS.TABLE_OF_SHOWBREAD,
    ],
    [TABERNACLE_PIECE_KEYS.FRONT_CURTAIN, TABERNACLE_PIECE_KEYS.INNER_CURTAIN],
    [TABERNACLE_PIECE_KEYS.FRONT_PILLARS, TABERNACLE_PIECE_KEYS.INNER_PILLARS],
    [TABERNACLE_PIECE_KEYS.WALLS],
    [TABERNACLE_PIECE_KEYS.BARS],
    [TABERNACLE_PIECE_KEYS.RINGS],
    [TABERNACLE_PIECE_KEYS.PURPLE_CURTAIN],
    [TABERNACLE_PIECE_KEYS.BROWN_CURTAIN],
    [TABERNACLE_PIECE_KEYS.RED_CURTAIN],
    [TABERNACLE_PIECE_KEYS.GREY_CURTAIN],
  ],
};
